name: Build and Deploy to Firebase

on:
  push:
    branches:
      - main
      - develop  

jobs:  

  build-prod:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.6'
          channel: 'stable'
      
      - name: Install dependencies
        run: flutter pub get
      - name: Create local.properties
        run: |
          echo "googleMapsApiKey=${{ secrets.GOOGLE_MAPS_API_KEY }}" > android/local.properties
      
      - name: Create .env file
        run: | 
          echo "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY_PROD }}" > .env.production
            
      - name: Run build_runner
        run: dart run build_runner build --delete-conflicting-outputs
      
      - name: Build APK (Prod)
        run: flutter build apk --release --flavor production -t lib/main_production.dart
      
      - name: Upload to Firebase (Prod)
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID_PROD }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: app tester
          file: build/app/outputs/flutter-apk/app-prod-release.apk
          releaseNotes: "Production Build - ${{ github.sha }}"
